export const DEFAULT_EXERCISES: { name: string; muscle_group: string; catalog_id: string | null }[] = [
  { name: 'Développé couché', muscle_group: 'Pectoraux', catalog_id: 'Barbell_Bench_Press_-_Medium_Grip' },
  { name: 'Développé incliné', muscle_group: 'Pectoraux', catalog_id: 'Incline_Barbell_Bench_Press' },
  { name: 'Développé décliné', muscle_group: 'Pectoraux', catalog_id: 'Decline_Barbell_Bench_Press' },
  { name: 'Écarté couché haltères', muscle_group: 'Pectoraux', catalog_id: 'Dumbbell_Flyes' },
  { name: 'Écarté à la poulie vis-à-vis', muscle_group: 'Pectoraux', catalog_id: 'Cable_Crossover' },
  { name: 'Pompes', muscle_group: 'Pectoraux', catalog_id: 'Pushups' },
  { name: 'Dips (pectoraux)', muscle_group: 'Pectoraux', catalog_id: 'Dips_-_Chest_Version' },
  { name: 'Tractions', muscle_group: 'Dos', catalog_id: 'Pullups' },
  { name: 'Rowing barre', muscle_group: 'Dos', catalog_id: 'Bent_Over_Barbell_Row' },
  { name: 'Rowing haltère', muscle_group: 'Dos', catalog_id: 'One-Arm_Dumbbell_Row' },
  { name: 'Tirage vertical', muscle_group: 'Dos', catalog_id: 'Wide-Grip_Lat_Pulldown' },
  { name: 'Tirage horizontal', muscle_group: 'Dos', catalog_id: 'Seated_Cable_Rows' },
  { name: 'Soulevé de terre', muscle_group: 'Dos', catalog_id: 'Barbell_Deadlift' },
  { name: 'Pull-over', muscle_group: 'Dos', catalog_id: 'Straight-Arm_Dumbbell_Pullover' },
  { name: 'Développé militaire', muscle_group: 'Épaules', catalog_id: 'Standing_Military_Press' },
  { name: 'Développé haltères assis', muscle_group: 'Épaules', catalog_id: 'Seated_Dumbbell_Press' },
  { name: 'Élévations latérales', muscle_group: 'Épaules', catalog_id: 'Side_Lateral_Raise' },
  { name: 'Élévations frontales', muscle_group: 'Épaules', catalog_id: 'Front_Dumbbell_Raise' },
  { name: 'Oiseau (élévations postérieures)', muscle_group: 'Épaules', catalog_id: 'Reverse_Flyes' },
  { name: 'Face pull', muscle_group: 'Épaules', catalog_id: 'Face_Pull' },
  { name: 'Shrugs', muscle_group: 'Épaules', catalog_id: 'Barbell_Shrug' },
  { name: 'Curl barre', muscle_group: 'Biceps', catalog_id: 'Barbell_Curl' },
  { name: 'Curl haltères', muscle_group: 'Biceps', catalog_id: 'Dumbbell_Bicep_Curl' },
  { name: 'Curl marteau', muscle_group: 'Biceps', catalog_id: 'Hammer_Curls' },
  { name: 'Curl incliné', muscle_group: 'Biceps', catalog_id: 'Incline_Dumbbell_Curl' },
  { name: 'Curl pupitre', muscle_group: 'Biceps', catalog_id: 'Preacher_Curl' },
  { name: 'Curl poulie basse', muscle_group: 'Biceps', catalog_id: 'Cable_Curl' },
  { name: 'Dips (triceps)', muscle_group: 'Triceps', catalog_id: 'Dips_-_Triceps_Version' },
  { name: 'Extension triceps poulie haute', muscle_group: 'Triceps', catalog_id: 'Triceps_Pushdown' },
  { name: 'Barre au front', muscle_group: 'Triceps', catalog_id: 'Lying_Triceps_Press' },
  { name: 'Extension triceps haltère', muscle_group: 'Triceps', catalog_id: 'Overhead_Triceps_Extension' },
  { name: 'Kickback', muscle_group: 'Triceps', catalog_id: 'Tricep_Dumbbell_Kickback' },
  { name: 'Développé couché prise serrée', muscle_group: 'Triceps', catalog_id: 'Close-Grip_Barbell_Bench_Press' },
  { name: 'Crunch', muscle_group: 'Abdominaux', catalog_id: 'Crunches' },
  { name: 'Crunch câble', muscle_group: 'Abdominaux', catalog_id: 'Cable_Crunch' },
  { name: 'Relevé de jambes', muscle_group: 'Abdominaux', catalog_id: 'Hanging_Leg_Raise' },
  { name: 'Planche', muscle_group: 'Abdominaux', catalog_id: 'Plank' },
  { name: 'Russian twist', muscle_group: 'Abdominaux', catalog_id: 'Russian_Twist' },
  { name: 'Ab wheel', muscle_group: 'Abdominaux', catalog_id: 'Ab_Roller' },
  { name: 'Squat', muscle_group: 'Quadriceps', catalog_id: 'Barbell_Squat' },
  { name: 'Squat bulgare', muscle_group: 'Quadriceps', catalog_id: 'Single_Leg_Squat' },
  { name: 'Presse à cuisses', muscle_group: 'Quadriceps', catalog_id: 'Leg_Press' },
  { name: 'Leg extension', muscle_group: 'Quadriceps', catalog_id: 'Leg_Extensions' },
  { name: 'Fentes', muscle_group: 'Quadriceps', catalog_id: 'Dumbbell_Lunges' },
  { name: 'Hack squat', muscle_group: 'Quadriceps', catalog_id: 'Hack_Squat' },
  { name: 'Leg curl couché', muscle_group: 'Ischios', catalog_id: 'Lying_Leg_Curls' },
  { name: 'Leg curl assis', muscle_group: 'Ischios', catalog_id: 'Seated_Leg_Curl' },
  { name: 'Soulevé de terre jambes tendues', muscle_group: 'Ischios', catalog_id: 'Stiff-Legged_Barbell_Deadlift' },
  { name: 'Good morning', muscle_group: 'Ischios', catalog_id: 'Good_Morning' },
  { name: 'Nordic curl', muscle_group: 'Ischios', catalog_id: 'Nordic_Hamstring_Curl' },
  { name: 'Hip thrust', muscle_group: 'Fessiers', catalog_id: 'Barbell_Hip_Thrust' },
  { name: 'Pont fessier', muscle_group: 'Fessiers', catalog_id: 'Glute_Bridge' },
  { name: 'Abduction hanche', muscle_group: 'Fessiers', catalog_id: 'Hip_Abduction_Machine' },
  { name: 'Kickback câble', muscle_group: 'Fessiers', catalog_id: 'Kneeling_Cable_Kickback' },
  { name: 'Fentes arrière', muscle_group: 'Fessiers', catalog_id: 'Dumbbell_Rear_Lunge' },
  { name: 'Mollets debout', muscle_group: 'Mollets', catalog_id: 'Standing_Calf_Raises' },
  { name: 'Mollets assis', muscle_group: 'Mollets', catalog_id: 'Seated_Calf_Raise' },
  { name: 'Mollets presse', muscle_group: 'Mollets', catalog_id: 'Calf_Press_On_The_Leg_Press_Machine' },
];
