export const DEFAULT_EXERCISES: { name: string; muscle_group: string; catalog_id: string | null }[] = [
  { name: 'Développé couché', muscle_group: 'Pectoraux', catalog_id: '0025' },
  { name: 'Développé incliné', muscle_group: 'Pectoraux', catalog_id: '0047' },
  { name: 'Développé décliné', muscle_group: 'Pectoraux', catalog_id: '0033' },
  { name: 'Écarté couché haltères', muscle_group: 'Pectoraux', catalog_id: '0308' },
  { name: 'Écarté à la poulie vis-à-vis', muscle_group: 'Pectoraux', catalog_id: '1269' },
  { name: 'Pompes', muscle_group: 'Pectoraux', catalog_id: '0662' },
  { name: 'Dips (pectoraux)', muscle_group: 'Pectoraux', catalog_id: '0251' },
  { name: 'Tractions', muscle_group: 'Dos', catalog_id: '0652' },
  { name: 'Rowing barre', muscle_group: 'Dos', catalog_id: '0027' },
  { name: 'Rowing haltère', muscle_group: 'Dos', catalog_id: '0293' },
  { name: 'Tirage vertical', muscle_group: 'Dos', catalog_id: '0150' },
  { name: 'Tirage horizontal', muscle_group: 'Dos', catalog_id: '0861' },
  { name: 'Soulevé de terre', muscle_group: 'Dos', catalog_id: '0032' },
  { name: 'Pull-over', muscle_group: 'Dos', catalog_id: '0375' },
  { name: 'Développé militaire', muscle_group: 'Épaules', catalog_id: '0091' },
  { name: 'Développé haltères assis', muscle_group: 'Épaules', catalog_id: '0405' },
  { name: 'Élévations latérales', muscle_group: 'Épaules', catalog_id: '0334' },
  { name: 'Élévations frontales', muscle_group: 'Épaules', catalog_id: '0310' },
  { name: 'Oiseau (élévations postérieures)', muscle_group: 'Épaules', catalog_id: '0380' },
  { name: 'Face pull', muscle_group: 'Épaules', catalog_id: null },
  { name: 'Shrugs', muscle_group: 'Épaules', catalog_id: '0095' },
  { name: 'Curl barre', muscle_group: 'Biceps', catalog_id: '0031' },
  { name: 'Curl haltères', muscle_group: 'Biceps', catalog_id: '0294' },
  { name: 'Curl marteau', muscle_group: 'Biceps', catalog_id: '0313' },
  { name: 'Curl incliné', muscle_group: 'Biceps', catalog_id: '0318' },
  { name: 'Curl pupitre', muscle_group: 'Biceps', catalog_id: '0070' },
  { name: 'Curl poulie basse', muscle_group: 'Biceps', catalog_id: '0868' },
  { name: 'Dips (triceps)', muscle_group: 'Triceps', catalog_id: '0814' },
  { name: 'Extension triceps poulie haute', muscle_group: 'Triceps', catalog_id: '0201' },
  { name: 'Barre au front', muscle_group: 'Triceps', catalog_id: '0060' },
  { name: 'Extension triceps haltère', muscle_group: 'Triceps', catalog_id: '0430' },
  { name: 'Kickback', muscle_group: 'Triceps', catalog_id: '0333' },
  { name: 'Développé couché prise serrée', muscle_group: 'Triceps', catalog_id: '0030' },
  { name: 'Crunch', muscle_group: 'Abdominaux', catalog_id: '0175' },
  { name: 'Crunch câble', muscle_group: 'Abdominaux', catalog_id: null },
  { name: 'Relevé de jambes', muscle_group: 'Abdominaux', catalog_id: '0472' },
  { name: 'Planche', muscle_group: 'Abdominaux', catalog_id: '0464' },
  { name: 'Russian twist', muscle_group: 'Abdominaux', catalog_id: '0687' },
  { name: 'Ab wheel', muscle_group: 'Abdominaux', catalog_id: '0857' },
  { name: 'Squat', muscle_group: 'Quadriceps', catalog_id: '0043' },
  { name: 'Squat bulgare', muscle_group: 'Quadriceps', catalog_id: '0411' },
  { name: 'Presse à cuisses', muscle_group: 'Quadriceps', catalog_id: '0739' },
  { name: 'Leg extension', muscle_group: 'Quadriceps', catalog_id: '0585' },
  { name: 'Fentes', muscle_group: 'Quadriceps', catalog_id: '0336' },
  { name: 'Hack squat', muscle_group: 'Quadriceps', catalog_id: '0743' },
  { name: 'Leg curl couché', muscle_group: 'Ischios', catalog_id: '0586' },
  { name: 'Leg curl assis', muscle_group: 'Ischios', catalog_id: '0599' },
  { name: 'Soulevé de terre jambes tendues', muscle_group: 'Ischios', catalog_id: '0432' },
  { name: 'Good morning', muscle_group: 'Ischios', catalog_id: '0044' },
  { name: 'Nordic curl', muscle_group: 'Ischios', catalog_id: null },
  { name: 'Hip thrust', muscle_group: 'Fessiers', catalog_id: null },
  { name: 'Pont fessier', muscle_group: 'Fessiers', catalog_id: '1409' },
  { name: 'Abduction hanche', muscle_group: 'Fessiers', catalog_id: '0597' },
  { name: 'Kickback câble', muscle_group: 'Fessiers', catalog_id: '0860' },
  { name: 'Fentes arrière', muscle_group: 'Fessiers', catalog_id: '0381' },
  { name: 'Mollets debout', muscle_group: 'Mollets', catalog_id: '1372' },
  { name: 'Mollets assis', muscle_group: 'Mollets', catalog_id: '0594' },
  { name: 'Mollets presse', muscle_group: 'Mollets', catalog_id: '1391' },
];
